#!/usr/bin/env python3
"""Generate a TabbyAPI config.yml from environment variables."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any


DEFAULT_MODEL = "gemma-4-31b-dense-exl3"


def env_bool(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None or raw == "":
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name: str, default: int) -> int:
    raw = os.environ.get(name)
    if raw is None or raw == "":
        return default
    return int(raw)


def env_float(name: str, default: float) -> float:
    raw = os.environ.get(name)
    if raw is None or raw == "":
        return default
    return float(raw)


def env_list(name: str, default: list[str]) -> list[str]:
    raw = os.environ.get(name)
    if raw is None or raw.strip() == "":
        return default
    return [part.strip() for part in raw.split(",") if part.strip()]


def env_float_list(name: str) -> list[float]:
    raw = os.environ.get(name)
    if raw is None or raw.strip() == "":
        return []
    return [float(part.strip()) for part in raw.split(",") if part.strip()]


def yaml_scalar(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return str(value)
    return json.dumps(str(value))


def yaml_list(values: list[Any]) -> str:
    return "[" + ", ".join(yaml_scalar(value) for value in values) + "]"


def normalize_cache_size(value: int) -> int:
    if value <= 0:
        return value
    return max(256, value - (value % 256))


def infer_tool_format(model_name: str) -> str:
    configured = os.environ.get("TABBY_TOOL_FORMAT")
    if configured:
        return configured
    lowered = model_name.lower()
    if "gemma" in lowered or "gemini" in lowered:
        return "gemma4"
    if "qwen" in lowered:
        return "qwen3_coder"
    return ""


def build_sampler_preset() -> str:
    settings: list[tuple[str, int | float]] = [
        ("temperature", env_float("TABBY_TEMPERATURE", 0.8)),
        ("top_p", env_float("TABBY_TOP_P", 0.95)),
        ("top_k", env_int("TABBY_TOP_K", 40)),
        ("mirostat_mode", env_int("TABBY_MIROSTAT", 2)),
        ("mirostat_tau", env_float("TABBY_MIROSTAT_TAU", 4.5)),
        ("mirostat_eta", env_float("TABBY_MIROSTAT_ETA", 0.1)),
        ("presence_penalty", env_float("TABBY_PRESENCE_PENALTY", 0.02)),
    ]
    lines = [
        "# Generated by scripts/tabbyapi_config.py.",
        "# Fallback sampler values only; request parameters still take precedence.",
    ]
    for name, value in settings:
        lines.extend(
            [
                f"{name}:",
                f"  override: {yaml_scalar(value)}",
                "  force: false",
            ]
        )
    return "\n".join(lines) + "\n"


def build_config(model_name: str | None = None) -> str:
    model_name = model_name or os.environ.get("TABBY_MODEL_NAME") or DEFAULT_MODEL
    context = env_int(
        "TABBY_CONTEXT_SIZE",
        env_int("CONTEXT_SIZE", 32768),
    )
    cache_size = normalize_cache_size(
        env_int("TABBY_CACHE_SIZE", env_int("TABBY_MAX_SEQ_LEN", context))
    )
    max_seq_len = env_int("TABBY_MAX_SEQ_LEN", context)
    tool_format = infer_tool_format(model_name)
    dummy_names = env_list(
        "TABBY_DUMMY_MODEL_NAMES",
        ["local", model_name, "gpt-3.5-turbo"],
    )
    if model_name not in dummy_names:
        dummy_names.insert(1, model_name)

    reasoning_default = bool(tool_format)
    force_thinking_default = tool_format == "gemma4"
    gpu_split = env_float_list("TABBY_GPU_SPLIT")
    gpu_split_auto_default = not gpu_split
    override_preset = os.environ.get("TABBY_OVERRIDE_PRESET", "qsa_coding")

    lines = [
        "# Generated by scripts/tabbyapi_config.py. Configure via TABBY_* env vars.",
        "network:",
        f"  host: {yaml_scalar(os.environ.get('TABBY_HOST', '0.0.0.0'))}",
        f"  port: {env_int('TABBY_PORT', 5000)}",
        f"  disable_auth: {yaml_scalar(env_bool('TABBY_DISABLE_AUTH', True))}",
        "  api_servers: [\"OAI\"]",
        "logging:",
        f"  log_prompt: {yaml_scalar(env_bool('TABBY_LOG_PROMPT', False))}",
        f"  log_generation_params: {yaml_scalar(env_bool('TABBY_LOG_GENERATION_PARAMS', False))}",
        f"  log_requests: {yaml_scalar(env_bool('TABBY_LOG_REQUESTS', False))}",
        "model:",
        f"  model_dir: {yaml_scalar(os.environ.get('TABBY_MODEL_DIR', 'models'))}",
        f"  inline_model_loading: {yaml_scalar(env_bool('TABBY_INLINE_MODEL_LOADING', False))}",
        f"  use_dummy_models: {yaml_scalar(env_bool('TABBY_USE_DUMMY_MODELS', True))}",
        f"  dummy_model_names: {yaml_list(dummy_names)}",
        f"  model_name: {yaml_scalar(model_name)}",
        f"  backend: {yaml_scalar(os.environ.get('TABBY_BACKEND', 'exllamav3'))}",
        f"  max_seq_len: {max_seq_len}",
        f"  cache_size: {cache_size}",
        f"  cache_mode: {yaml_scalar(os.environ.get('TABBY_CACHE_MODE', 'Q8'))}",
        f"  tensor_parallel: {yaml_scalar(env_bool('TABBY_TENSOR_PARALLEL', False))}",
        f"  tensor_parallel_backend: {yaml_scalar(os.environ.get('TABBY_TENSOR_PARALLEL_BACKEND', 'native'))}",
        f"  gpu_split_auto: {yaml_scalar(env_bool('TABBY_GPU_SPLIT_AUTO', gpu_split_auto_default))}",
        f"  autosplit_reserve: [{env_int('TABBY_AUTOSPLIT_RESERVE_MIB', 1024)}]",
        f"  gpu_split: {yaml_list(gpu_split)}",
        f"  chunk_size: {env_int('TABBY_CHUNK_SIZE', 2048)}",
        f"  output_chunking: {yaml_scalar(env_bool('TABBY_OUTPUT_CHUNKING', True))}",
        f"  max_batch_size: {env_int('TABBY_MAX_BATCH_SIZE', 1)}",
        f"  force_enable_thinking: {yaml_scalar(env_bool('TABBY_FORCE_ENABLE_THINKING', force_thinking_default))}",
        f"  reasoning: {yaml_scalar(env_bool('TABBY_REASONING', reasoning_default))}",
        f"  reasoning_start_token: {yaml_scalar(os.environ.get('TABBY_REASONING_START_TOKEN', '<think>'))}",
        f"  reasoning_end_token: {yaml_scalar(os.environ.get('TABBY_REASONING_END_TOKEN', '</think>'))}",
        f"  tool_format: {yaml_scalar(tool_format)}",
        "sampling:",
        f"  override_preset: {yaml_scalar(override_preset)}",
        "memory:",
        f"  cuda_malloc_async: {yaml_scalar(env_bool('TABBY_CUDA_MALLOC_ASYNC', True))}",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model-name")
    parser.add_argument("--write", type=Path)
    parser.add_argument(
        "--write-sampler-preset",
        type=Path,
        help="Write the generated sampler override preset used by config.yml.",
    )
    args = parser.parse_args(argv)

    config = build_config(args.model_name)
    if args.write_sampler_preset:
        args.write_sampler_preset.parent.mkdir(parents=True, exist_ok=True)
        args.write_sampler_preset.write_text(build_sampler_preset(), encoding="utf-8")
    if args.write:
        args.write.parent.mkdir(parents=True, exist_ok=True)
        args.write.write_text(config, encoding="utf-8")
    else:
        print(config, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
